- name: Download python3
  unarchive:
    src: "{{ py3distr }}"
    dest: /tmp
    copy: no

- name: Install python3
  shell: "{{ item }} chdir=/tmp/{{ py3folder }}"
  with_items:
    - ./configure
    - make
    - make install

- name: Delete temporary files
  file:
    path: /tmp/{{ py3folder }}
    state: absent

- name: Install and update pip
  shell: "python3 -m pip install pip --upgrade"

- name: Update setuptools
  shell: "python3 -m pip install setuptools --upgrade"
